services:
   
   #FastAPI Application


   #Nginx Services



   #Qdrant (vectorDB)


   #Prometheus Monitoring



   #Grafana Dashboard


   #Node Exporter For system metrics



   #PostgreSQL Exporter for postgres matrics
   
   
         

